<!-- body //-->
<div id="dsContent">
    <div class="dsMETAleft">
        <div class="breadCrumb">
        	<ul>
				<li><a href="<?php echo dsf_link('index.html');?>"><?php echo TRANSLATION_HOME;?></a></li>
            	<li><a href="<?php echo dsf_link('agb-onlineshop.html');?>"><?php echo TRANSLATION_CUSTOM_TEXT_SEVEN;?></a></li>
			</ul>
		</div>
		<div class="clear"></div>
            <h1><?php echo ds_strtoupper(TRANSLATION_CUSTOM_TEXT_SEVEN); ?></h1>
<p>F&uuml;r alle Gesch&auml;ftsbeziehungen zwischen der VARTA Consumer Batteries GmbH &amp; Co. KGaA, Alfred-Krupp-Stra&szlig;e 9, 73479 Ellwangen (&bdquo;VARTA CONSUMER&ldquo;) und Ihnen gelten ausschlie&szlig;lich die nachfolgenden Allgemeinen Gesch&auml;ftsbedingungen (&bdquo;AGB&ldquo;) in der zum Zeitpunkt Ihrer Bestellung g&uuml;ltigen Fassung.</p>
<p><strong>Allgemeines</strong></p>
<p>Mit der Bestellung einer Ware bei VARTA CONSUMER erkennen Sie diese AGB an. Anderslautende Bedingungen finden keine Anwendung, es sei denn wir h&auml;tten diesen Bedingungen ausdr&uuml;cklich schriftlich zugestimmt. Eine Belieferung erfolgt ausschlie&szlig;lich an Personen mit Wohnsitz/Gesch&auml;ftssitz in Deutschland. Bestellungen k&ouml;nnen nur in haushalts&uuml;blichen Mengen erfolgen.</p>
<p><strong>Vertragsschluss</strong></p>
<p>Sie k&ouml;nnen Ihre Bestellung online, telefonisch unter 00800 830 700 83 oder per E-Mail an <a href="mailto:service@eu.russellhobbs.com">service@eu.russellhobbs.com</a> aufgeben. Den Eingang Ihrer Bestellung und deren Einzelheiten best&auml;tigen wir per E-Mail oder per Brief (Bestellbest&auml;tigung). Diese Bestellbest&auml;tigung stellt keine Annahme Ihrer Bestellung dar, sondern soll Sie nur dar&uuml;ber informieren, dass Ihr Auftrag bei uns eingegangen ist. Ein Vertrag kommt in jedem Falle erst dann zu Stande, wenn wir die bestellte Ware an Sie versenden und den Versand an Sie mit einer zweiten E-Mail (Versandbest&auml;tigung) best&auml;tigen.</p>
<p><strong>Preise, Verf&uuml;gbarkeit, Versand, R&uuml;cksendekosten bei Widerruf</strong></p>
<p>Alle Preise sind Endpreise, sie enthalten die gesetzliche Mehrwertsteuer, aber nicht die Liefer- und Versandkosten, welche jeweils gesondert ausgewiesen werden.</p>
<p>Angaben &uuml;ber die Verf&uuml;gbarkeit von Ware im Onlineshop oder am Telefon sind lediglich Richtwerte. Da eine Bestellung auf verschiedene Weise erfolgen kann, ist es m&ouml;glich, dass eine Ware bereits ausverkauft ist, obwohl im Onlineshop die Ware noch als verf&uuml;gbar angezeigt oder bei telefonischer Bestellung durch unseren Mitarbeiter noch als verf&uuml;gbar bezeichnet wird.</p>
<p>Bei einem Bestellwert von unter EUR 50,00 betragen die Kosten f&uuml;r den Warenversand innerhalb Deutschlands EUR 4,99. Bei einem Bestellwert von &uuml;ber EUR 50,00 ist der Warenversand f&uuml;r Sie kostenlos.</p>
<p>Soweit Sie von einem bestehenden Widerrufsrecht Gebrauch machen, haben Sie die regelm&auml;&szlig;igen Kosten der R&uuml;cksendung zu tragen, wenn die gelieferte Ware der bestellten entspricht und wenn der Preis der zur&uuml;ckzusendenden Sache einen Betrag von EUR&nbsp;40,00 nicht &uuml;bersteigt, oder wenn Sie bei einem h&ouml;heren Preis der Sache zum Zeitpunkt des Widerrufs noch nicht die Gegenleistung oder eine vertraglich vereinbarte Teilzahlung erbracht haben. Anderenfalls ist die R&uuml;cksendung f&uuml;r Sie kostenfrei.</p>
<p><strong>Zahlungsbedingungen</strong></p>
<p>Bei der Bestellung per Telefon oder E-Mail verlangen wir Vorauskasse, bei der Online-Bestellung k&ouml;nnen Sie alternativ dazu auch per Kreditkarte oder per Lastschrifteinzug zahlen. Wir behalten uns vor, bestimmte Zahlungsarten im Einzelfall auszuschlie&szlig;en.</p>
<p>Unsere Rechnungen sind, sofern nicht schriftlich etwas anderes vereinbart wurde, sofort und ohne Abzug zahlbar.&nbsp;</p>
<p><strong>Eigentumsvorbehalt</strong></p>
<p>Die gelieferte Ware bleibt bis zum Eingang der vollst&auml;ndigen Bezahlung aller Forderungen unser Eigentum.</p>
<p><strong>M&auml;ngelanspr&uuml;che, Haftungsbeschr&auml;nkung</strong></p>
<p>Ihre M&auml;ngelanspr&uuml;che richten sich nach den gesetzlichen Bestimmungen. Bitte wenden Sie sich bei M&auml;ngelanspr&uuml;chen an unser:</p>
<p>Russell Hobbs Service Center<br />c/o CONVAR Deutschland GmbH<br />Massachusetts Avenue 4600<br />66953 Pirmasens<br />Telefon: 00800 830 700 83<br />E-Mail: <a href="mailto:service@eu.russellhobbs.com">service@eu.russellhobbs.com</a></p>
<p>Soweit sich nachstehend nichts Anderes ergibt, sind weitergehende Schadenersatzanspr&uuml;che &ndash; gleich aus welchen Rechtsgr&uuml;nden &ndash; ausgeschlossen. Wir haften insbesondere nicht f&uuml;r entgangenen Gewinn oder f&uuml;r sonstige Verm&ouml;genssch&auml;den.</p>
<p>Vorstehende Haftungsbeschr&auml;nkung gilt nicht, soweit die Schadensursache auf Vorsatz oder grober Fahrl&auml;ssigkeit beruht oder ein Personenschaden vorliegt. Sie gilt ferner dann nicht, wenn Sie Anspr&uuml;che aus dem Produkthaftungsgesetz geltend machen.</p>
<p>Soweit unsere Haftung ausgeschlossen oder beschr&auml;nkt ist, gilt dies auch f&uuml;r die pers&ouml;nliche Haftung von Arbeitnehmern, Vertretern und Erf&uuml;llungsgehilfen.<br /></p>
<h2>Widerrufsbelehrung</h2>
<p><strong>Widerrufsrecht</strong></p>
<p><strong>Sie k&ouml;nnen Ihre Vertragserkl&auml;rung innerhalb von 14 Tagen ohne Angabe von Gr&uuml;nden in Textform (z.B. Brief, Fax, E-Mail) oder &ndash; wenn Ihnen die Ware vor Fristablauf &uuml;berlassen wird &ndash; durch R&uuml;cksendung der Ware widerrufen, es sei denn, Sie haben nicht als Verbraucher, sondern in Aus&uuml;bung Ihrer gewerblichen oder selbst&auml;ndigen beruflichen T&auml;tigkeit gehandelt. Die Frist beginnt nach Erhalt dieser Belehrung in Textform, jedoch nicht vor Eingang der Ware bei Ihnen und auch nicht vor Erf&uuml;llung unserer Informationspflichten gem&auml;&szlig; Artikel 246 &sect;&nbsp;2 in Verbindung mit &sect;&nbsp;1 Abs. 1 und 2 EGBGB und unserer Pflichten gem&auml;&szlig; &sect;&nbsp;312g Abs. 1 Satz 1 BGB in Verbindung mit Artikel 246 &sect;&nbsp;3 EGBGB. Zur Wahrung der Widerrufsfrist gen&uuml;gt die rechtzeitige Absendung des Widerrufs oder der Ware. Der Widerruf ist zu richten an:</strong></p>
<p><strong>Russell Hobbs Service Center<br />c/o CONVAR Deutschland GmbH<br />Massachusetts Avenue 4600<br />66953 Pirmasens<br />Fax: 06331 268 623<br />E-Mail: <a href="mailto:service@eu.russellhobbs.com">service@eu.russellhobbs.com</a></strong></p>
<p><strong>Widerrufsfolgen</strong></p>
<p><strong>Im Falle eines wirksamen Widerrufs sind die beiderseits empfangenen Leistungen zur&uuml;ckzugew&auml;hren und ggf. gezogene Nutzungen herauszugeben. K&ouml;nnen Sie uns die empfangene Leistung sowie Nutzungen (z.B. Gebrauchsvorteile) nicht oder teilweise nicht oder nur in verschlechtertem Zustand zur&uuml;ckgew&auml;hren beziehungsweise herausgeben, m&uuml;ssen Sie uns insoweit Wertersatz leisten. F&uuml;r die Verschlechterung der Sache und f&uuml;r gezogene Nutzungen m&uuml;ssen Sie Wertersatz nur leisten, soweit die Nutzungen oder die Verschlechterung auf einen Umgang mit der Sache zur&uuml;ckzuf&uuml;hren ist, der &uuml;ber die Pr&uuml;fung der Eigenschaften und der Funktionsweise hinausgeht. Unter &bdquo;Pr&uuml;fung der Eigenschaften und der Funktionsweise&ldquo; versteht man das Testen und Ausprobieren der jeweiligen Ware, wie es etwa im Ladengesch&auml;ft m&ouml;glich und &uuml;blich ist. Paketversandf&auml;hige Waren sind auf unsere Gefahr zur&uuml;ckzusenden. Sie haben die regelm&auml;&szlig;igen Kosten der R&uuml;cksendung zu tragen, wenn die gelieferte Ware der bestellten entspricht und wenn der Preis der zur&uuml;ckzusendenden Ware einen Betrag von EUR 40,00 nicht &uuml;bersteigt oder wenn Sie bei einem h&ouml;heren Preis der Ware zum Zeitpunkt des Widerrufs noch nicht die Gegenleistung oder eine vertraglich vereinbarte Teilzahlung erbracht haben. Anderenfalls ist die R&uuml;cksendung f&uuml;r Sie kostenfrei. Nicht paketversandf&auml;hige Sachen werden bei Ihnen abgeholt. Verpflichtungen zur Erstattung von Zahlungen m&uuml;ssen innerhalb von 30 Tagen erf&uuml;llt werden. Die Frist beginnt f&uuml;r Sie mit der Absendung Ihrer Widerrufserkl&auml;rung oder der Ware, f&uuml;r uns mit deren Empfang.</strong></p>
<p><strong>Ende der Widerrufsbelehrung</strong></p>
<p><strong>Abwicklung der R&uuml;cksendung bei Waren mit einem Wert von &uuml;ber EUR 40,00</strong></p>
<p>Um eine sichere und komfortable Abwicklung der R&uuml;cksendung zu erm&ouml;glichen, empfehlen wir folgende Vorgehensweise:</p>
<p>Bitte rufen Sie zun&auml;chst die kostenfreie Telefonnummer unseres Servicecenters an: 00800 830 700 83. Unser Servicecenter wird Ihnen eine Retourennummer mitteilen, welche die kostenfreie Abholung der Ware durch den Express- und Paketzustelldienst UPS erm&ouml;glicht. Im Anschluss k&ouml;nnen Sie telefonisch unter 01805 882 663 &nbsp;direkt mit UPS einen f&uuml;r Sie passenden Termin f&uuml;r die Abholung bei Ihnen Zuhause vereinbaren.</p>
<p><strong>Erhebung und Verwendung von Daten</strong></p>
<p>Die uns im Rahmen der Gesch&auml;ftsbeziehung mit Ihnen bekannt gewordenen personenbezogenen Daten, z.B. Ihr Name und Ihre Kontaktdaten, speichern und verwenden wir nur zum Zwecke der Vertragserf&uuml;llung. Wir geben Ihre Daten nur an das mit der Lieferung beauftragte Versandunternehmen weiter, soweit dies zur Lieferung der Waren notwendig ist. Zur Abwicklung von Zahlungen geben wir Ihre Zahlungsdaten an das mit der Zahlung beauftragte Kreditinstitut weiter.</p>
<p>Sollten Sie mit der Speicherung Ihrer personenbezogenen Daten nicht mehr einverstanden sein oder diese unrichtig geworden sein, werden wir auf eine entsprechende Weisung hin im Rahmen der gesetzlichen Bestimmungen die L&ouml;schung, Korrektur oder Sperrung Ihrer Daten veranlassen. Auf Wunsch erhalten Sie unentgeltlich Auskunft &uuml;ber alle bei uns gespeicherten personenbezogenen Daten von Ihnen.</p>
<p>Weitere Einzelheiten zur Verarbeitung von Daten, etwa bei Besuch unserer Website, sind in unserer <a href="http://de.russellhobbs.com/privacy.html">Datenschutzerkl&auml;rung</a> geregelt.</p>
<p><strong>Schlussbestimmungen</strong></p>
<p>Es gilt deutsches Recht unter Ausschluss der Regelungen zum internationalen Warenkauf (UN-Kaufrecht, CISG) und des internationalen Privatrechts.</p>
<p>Gerichtsstand f&uuml;r alle Streitigkeiten aus oder im Zusammenhang mit dem Vertrag ist Frankfurt am Main, sofern Sie Kaufmann, juristische Person des &ouml;ffentlichen Rechts oder &ouml;ffentlich-rechtliches Sonderverm&ouml;gen sind.</p>
<p>Sollte eine der Bestimmungen ganz oder teilweise unwirksam sein oder werden, bleiben die &uuml;brigen Bestimmungen wirksam. Anstelle der unwirksamen Bestimmung gilt eine Bestimmung als vereinbart, die dem von den Parteien beabsichtigten wirtschaftlichen Zweck der fehlenden oder unwirksamen Bestimmung am n&auml;chsten kommt.</p>
<p>Stand: September 2011</p>
            </div>
            </div>
