<!-- body //-->
<div id="dsContent">
	<div class="breadCrumb">
    	<ul>
        	<li><a href="<?php echo dsf_link('index.html');?>"><?php echo ds_strtoupper(TRANSLATION_HOME);?></a></li>
            <li><a href="<?php echo dsf_link('recycling.html');?>"><?php echo ds_strtoupper(TRANSLATION_RECYCLING);?></a></li>
        </ul>
    </div>
    <div class="clear"></div>
    <div class="dsTCContent">
    	<h1><?php echo ds_strtoupper(TRANSLATION_RECYCLING);?></h1>
        <p><?php echo dsf_image('custom/recycling_wee.gif', 'Recycling', '75', '75', 'class="dsWRImg"');?>&Alpha;&pi;&#972; &tau;&eta;&nu; 1&eta; &Iota;&omicron;&upsilon;&lambda;&#943;&omicron;&upsilon; 2007, &nu;&#941;&omicron;&iota; &kappa;&alpha;&nu;&omicron;&nu;&iota;&sigma;&mu;&omicron;&#943; &omicron;&iota; &omicron;&pi;&omicron;&#943;&omicron;&iota; &omicron;&nu;&omicron;&mu;&#940;&zeta;&omicron;&nu;&tau;&alpha;&iota; &Kappa;&alpha;&nu;&omicron;&nu;&iota;&sigma;&mu;&omicron;&#943; &Alpha;&pi;&omicron;&beta;&lambda;&#942;&tau;&omega;&nu; &Eta;&lambda;&epsilon;&kappa;&tau;&rho;&iota;&kappa;&omicron;&#973; &kappa;&alpha;&iota; &Eta;&lambda;&epsilon;&kappa;&tau;&rho;&omicron;&nu;&iota;&kappa;&omicron;&#973; &Epsilon;&xi;&omicron;&pi;&lambda;&iota;&sigma;&mu;&omicron;&#973; (&Alpha;&Eta;&Eta;&Epsilon;) &tau;&#941;&theta;&eta;&kappa;&alpha;&nu; &sigma;&epsilon; &iota;&sigma;&chi;&#973; &#974;&sigma;&tau;&epsilon; &nu;&alpha; &epsilon;&nu;&theta;&alpha;&rho;&rho;&#973;&nu;&omicron;&upsilon;&nu; &tau;&omicron;&upsilon;&sigmaf; &alpha;&nu;&theta;&rho;&#974;&pi;&omicron;&upsilon;&sigmaf; &nu;&alpha; &omicron;&rho;&gamma;&alpha;&nu;&#974;&sigma;&omicron;&upsilon;&nu; &tau;&eta; &sigma;&upsilon;&lambda;&lambda;&omicron;&gamma;&#942; &#942; &tau;&eta;&nu; &alpha;&nu;&alpha;&kappa;&#973;&kappa;&lambda;&omega;&sigma;&eta; &tau;&omega;&nu; &pi;&alpha;&lambda;&alpha;&iota;&#974;&nu; &eta;&lambda;&epsilon;&kappa;&tau;&rho;&iota;&kappa;&#974;&nu; &pi;&rho;&omicron;&#970;&#972;&nu;&tau;&omega;&nu;, &alpha;&nu;&tau;&#943; &nu;&alpha; &tau;&alpha; &pi;&epsilon;&tau;&omicron;&#973;&nu;.</p>
        <p><strong>&Gamma;&iota;&alpha;&tau;&#943; &epsilon;&#943;&nu;&alpha;&iota; &sigma;&eta;&mu;&alpha;&nu;&tau;&iota;&kappa;&#942;  &eta; &alpha;&nu;&alpha;&kappa;&#973;&kappa;&lambda;&omega;&sigma;&eta; &eta;&lambda;&epsilon;&kappa;&tau;&rho;&iota;&kappa;&#974;&nu; &sigma;&upsilon;&sigma;&kappa;&epsilon;&upsilon;&#974;&nu;;</strong><br />
  &Eta; &Alpha;&nu;&alpha;&kappa;&#973;&kappa;&lambda;&omega;&sigma;&eta; &Eta;&lambda;&epsilon;&kappa;&tau;&rho;&iota;&kappa;&#974;&nu; &alpha;&nu;&epsilon;&pi;&iota;&theta;&#973;&mu;&eta;&tau;&omega;&nu; &pi;&rho;&omicron;&#970;&#972;&nu;&tau;&omega;&nu; &epsilon;&#943;&nu;&alpha;&iota; &kappa;&alpha;&lambda;&#973;&tau;&epsilon;&rho;&eta; &gamma;&iota;&alpha; &tau;&omicron; &pi;&epsilon;&rho;&iota;&beta;&#940;&lambda;&lambda;&omicron;&nu;. &Eta;&lambda;&epsilon;&kappa;&tau;&rho;&omicron;&nu;&iota;&kappa;&#941;&sigmaf; &sigma;&upsilon;&sigma;&kappa;&epsilon;&upsilon;&#941;&sigmaf; &kappa;&alpha;&iota; &mu;&pi;&alpha;&tau;&alpha;&rho;&#943;&epsilon;&sigmaf;, &epsilon;&pi;&alpha;&nu;&alpha;&phi;&omicron;&rho;&tau;&iota;&zeta;&#972;&mu;&epsilon;&nu;&epsilon;&sigmaf; &#942; &mu;&eta;, &delta;&epsilon;&nu; &pi;&rho;&#941;&pi;&epsilon;&iota; &nu;&alpha; &alpha;&pi;&omicron;&rho;&rho;&#943;&pi;&tau;&omicron;&nu;&tau;&alpha;&iota; &sigma;&tau;&alpha; &kappa;&alpha;&nu;&omicron;&nu;&iota;&kappa;&#940; &omicron;&iota;&kappa;&iota;&alpha;&kappa;&#940; &alpha;&pi;&#972;&beta;&lambda;&eta;&tau;&alpha;. &Alpha;&nu;&tau;' &alpha;&upsilon;&tau;&omicron;&#973;, &theta;&alpha; &pi;&rho;&#941;&pi;&epsilon;&iota; &nu;&alpha; &alpha;&nu;&alpha;&kappa;&upsilon;&kappa;&lambda;&#974;&nu;&omicron;&nu;&tau;&alpha;&iota; &sigma;&omega;&sigma;&tau;&#940; &#974;&sigma;&tau;&epsilon; &nu;&alpha; &pi;&rho;&omicron;&sigma;&tau;&alpha;&tau;&epsilon;&#973;&epsilon;&tau;&alpha;&iota; &tau;&omicron; &pi;&epsilon;&rho;&iota;&beta;&#940;&lambda;&lambda;&omicron;&nu; &kappa;&alpha;&iota; &nu;&alpha; &pi;&epsilon;&rho;&iota;&omicron;&rho;&iota;&sigma;&tau;&epsilon;&#943; &eta; &sigma;&pi;&alpha;&tau;&#940;&lambda;&eta; &pi;&omicron;&lambda;&#973;&tau;&iota;&mu;&omega;&nu; &pi;&#972;&rho;&omega;&nu;.</p>
        <p><strong> &Pi;&#974;&sigmaf; &mu;&pi;&omicron;&rho;&#974; &nu;&alpha; &alpha;&nu;&alpha;&kappa;&upsilon;&kappa;&lambda;&#974;&sigma;&omega; &pi;&alpha;&lambda;&iota;&#940; &eta;&lambda;&epsilon;&kappa;&tau;&rho;&iota;&kappa;&#940; &pi;&rho;&omicron;&#970;&#972;&nu;&tau;&alpha;;</strong><br />
  &Omicron; &Delta;&#942;&mu;&omicron;&sigmaf; &sigma;&alpha;&sigmaf; &kappa;&alpha;&iota; &eta; &alpha;&rho;&chi;&#942; &delta;&iota;&alpha;&chi;&epsilon;&#943;&rho;&iota;&sigma;&eta;&sigmaf; &tau;&omega;&nu; &alpha;&pi;&omicron;&beta;&lambda;&#942;&tau;&omega;&nu; &theta;&alpha; &epsilon;&#943;&nu;&alpha;&iota; &sigma;&epsilon; &theta;&#941;&sigma;&eta; &nu;&alpha; &sigma;&alpha;&sigmaf; &epsilon;&nu;&eta;&mu;&epsilon;&rho;&#974;&sigma;&omicron;&upsilon;&nu; &kappa;&alpha;&iota; &nu;&alpha; &sigma;&alpha;&sigmaf; &sigma;&upsilon;&mu;&beta;&omicron;&upsilon;&lambda;&#941;&psi;&omicron;&upsilon;&nu; &sigma;&chi;&epsilon;&tau;&iota;&kappa;&#940; &mu;&epsilon; &tau;&eta;&nu; &alpha;&nu;&alpha;&kappa;&#973;&kappa;&lambda;&omega;&sigma;&eta; &sigma;&tau;&eta;&nu; &pi;&epsilon;&rho;&iota;&omicron;&chi;&#942; &sigma;&alpha;&sigmaf;.</p>
    </div>
    <?php include ('custom_modules/default/meta_menu.php');?>
    <div class="metaDShade"></div>
    <div class="clear"></div>
</div>